export default [
  { name: "Michael Zhao", team: "Advisor" },
  { name: "Salman Jaher", team: "Director" },
  { name: "Purva Pawar", team: "Director" },
  { name: "Joshua (Josh) Das", team: "Experience" },
  { name: "Evan Ngo", team: "Experience" },
  { name: "Reiki Hingorani", team: "Experience" },
  { name: "Alan Roybal", team: "Experience" },
  { name: "Veer Shah", team: "Experience" },
  { name: "Arjun Kumar", team: "Experience" },
  { name: "Daniel Kim", team: "Experience" },
  { name: "Adelaide (Addy) Dunning", team: "Logistics" },
  { name: "Anwita Gudapurri", team: "Logistics" },
  { name: "Shreya Mekala", team: "Logistics" },
  { name: "Roshni Reddhannan", team: "Logistics" },
  { name: "Sahishnu Sagiraju", team: "Logistics" },
  { name: "Bhuvana Madiraju", team: "Industry" },
  { name: "Sharun Naicker", team: "Industry" },
  { name: "Sachi Hansalia", team: "Industry" },
  { name: "Ridwan Amin", team: "Industry" },
  { name: "Bryan Caraman", team: "Industry" },
  { name: "John Luke", team: "Industry" },
  { name: "Mike Nguyen", team: "Tech" },
  { name: "Wei Seng", team: "Tech" },
  { name: "Rayyan Waris", team: "Tech" },
  { name: "Victoria Vynnychok", team: "Tech" },
  { name: "Tu Do", team: "Tech" },
  { name: "Kelly Zhou", team: "Marketing" },
  { name: "Mitchell Vu", team: "Marketing" },
  { name: "Shaswat (Shaz) Kumar", team: "Marketing" },
  { name: "Alyssa To", team: "Marketing" },
  { name: "Ann Jayan", team: "Marketing" },
  { name: "Sarah Jacob", team: "Marketing" },
  { name: "Caleb Bae", team: "Marketing" },
  { name: "Fatin Chad", team: "Finance" },
  { name: "Ayusha Timalsena", team: "Finance" },
];
