export default [
    { name: "Michael Zhao", team: "Director" },
    { name: "Shreya Kuntumalla", team: "Industry" },
    { name: "Dylan Nguyen", team: "Marketing" },
    { name: "Muskaan Bansal", team: "Logistics" },
    { name: "Joshua (Josh) Das", team: "Experience" },
    { name: "Nick Burnett", team: "Tech" },
    { name: "Abdullah Hasani", team: "Finance" },
    { name: "Bhuvana Madiraju", team: "Industry" },
    { name: "Esmond Tsang", team: "Industry" },
    { name: "Farhan Jamil", team: "Industry" },
    { name: "Parth Amrute", team: "Industry" },
    { name: "Purva Pawar", team: "Industry" },
    { name: "Sharun Naicker", team: "Industry" },
    { name: "Kelly Zhou", team: "Marketing" },
    { name: "Lisa Wu", team: "Marketing" },
    { name: "Mitchell Vu", team: "Marketing" },
    { name: "Shaswat (Shaz) Kumar", team: "Marketing" },
    { name: "Shoaib Huq", team: "Marketing" },
    { name: "Jordan Tan", team: "Marketing" },
    { name: "Abigail Smith", team: "Logistics" },
    { name: "Adelaide (Addy) Dunning", team: "Logistics" },
    { name: "Arjun Kumar", team: "Logistics" },
    { name: "Caleb Lim", team: "Logistics" },
    { name: "Shagun Dalal", team: "Logistics" },
    { name: "Daniel Liu", team: "Experience" },
    { name: "Salman Jaher", team: "Experience" },
    { name: "Kevin Ge", team: "Experience" },
    { name: "Evan Ngo", team: "Experience" },
    { name: "Amrit Rathie", team: "Tech" },
    { name: "Geeth Gunnampalli", team: "Tech" },
    { name: "Mike Nguyen", team: "Tech" },
    { name: "Nam Truong", team: "Tech" },
]
